name: Build, Parsing, Leaks and Standard Compliance (Norm) check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libxext-dev libx11-dev libbsd-dev

      - name: Build cub3D
        run: make

      - name: Check standard compliance (Norm)
        continue-on-error: true
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
          norminette lib/libft/ include/ src/

      - name: Check leaks on invalid maps (Valgrind)
        run: |
          PROGRAM=./cub3D
          MAP_DIRS=("assets/maps/invalid/color" "assets/maps/invalid/content" \
          "assets/maps/invalid/tex")
          for DIR in "${MAP_DIRS[@]}"; do
              for MAP in "$DIR"/*; do
                  [ -f "$MAP" ] || continue
                  valgrind --leak-check=full --error-exitcode=1 "$PROGRAM" "$MAP" || exit 1
              done
          done
